Repository UKHomeOffice/core-cloud-dns-terraform, pull requests merged in 2025-04, with the labels that each got.

#1 CCL-2378: CC DNS R53 Profile Config
  .github/dependabot.yaml
  .github/workflows/pull-request-sast.yaml
  .github/workflows/pull-request-semver-label-check.yaml
  .github/workflows/pull-request-semver-tag-merge.yaml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE.md
  README.md
  main.tf
  r53-profile/outputs.tf
  r53-profile/r53-inbound-resolver-endpoints.tf
  r53-profile/r53-inbound-resolver-rules.tf
  r53-profile/r53-outbound-resolver-endpoints.tf
  r53-profile/r53-outbound-resolver-rules.tf
  r53-profile/r53-profile-ram-share.tf
  r53-profile/r53-profile.tf
  r53-profile/security-groups.tf
  r53-profile/variables.tf
  variables.tf
Labels: major

#2 CCL-2379/DNS Firewall config
  main.tf
  r53-profile/r53-firewall.tf
  r53-profile/r53-inbound-resolver-endpoints.tf
  r53-profile/r53-outbound-resolver-endpoints.tf
  r53-profile/r53-outbound-resolver-rules.tf
  r53-profile/r53-profile-ram-share.tf
  r53-profile/r53-profile.tf
  r53-profile/security-groups.tf
  r53-profile/variables.tf
  variables.tf
Labels: minor

#3 updating the custom_block_rule
  r53-profile/r53-firewall.tf
  r53-profile/variables.tf
  variables.tf
Labels: minor

#4 updated main.tf
  main.tf
Labels: minor

#6 updated priority variables
  main.tf
  r53-profile/r53-firewall.tf
  r53-profile/variables.tf
  variables.tf
Labels: minor

#7 CCL-2405 - Adding component catalog yaml file
  catalog-info.yaml
Labels: patch

#8 CCL-2662: PDNS changes including subnet refactoring
  main.tf
  modules/r53-profile/outputs.tf
  modules/r53-profile/r53-firewall.tf
  modules/r53-profile/r53-inbound-resolver-endpoints.tf
  modules/r53-profile/r53-inbound-resolver-rules.tf
  modules/r53-profile/r53-outbound-resolver-endpoints.tf
  modules/r53-profile/r53-outbound-resolver-rules.tf
  modules/r53-profile/r53-profile-ram-share.tf
  modules/r53-profile/r53-profile.tf
  modules/r53-profile/resolver-outbound-endpoint-routing.tf
  modules/r53-profile/security-groups.tf
  modules/r53-profile/variables.tf
  r53-profile/r53-inbound-resolver-endpoints.tf
  r53-profile/r53-outbound-resolver-endpoints.tf
  r53-profile/r53-outbound-resolver-rules.tf
  r53-profile/security-groups.tf
  variables.tf
Labels: minor
